import express from 'express';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';
import { db } from './db.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const agentWindowsDir = path.join(__dirname, '..', '..', 'agent', 'windows');

export const downloadRouter = express.Router();

function publicBase(req) {
  const fromQuery = (req.query.server || '').toString().trim();
  if (fromQuery) return fromQuery.replace(/\/$/, '');
  const proto = (req.headers['x-forwarded-proto'] || req.protocol || 'http').toString().split(',')[0].trim();
  const host = (req.headers['x-forwarded-host'] || req.headers.host || 'localhost:8787').toString();
  return `${proto}://${host}`.replace(/\/$/, '');
}

function resolveEnrollmentKey(req) {
  const key = (req.query.key || '').toString().trim();
  if (key) {
    const row = db.prepare(
      'SELECT key_value FROM enrollment_keys WHERE key_value = ? AND revoked = 0'
    ).get(key);
    if (!row) return { error: 'Invalid or revoked enrollment key', status: 403 };
    return { key: row.key_value };
  }
  const latest = db.prepare(
    'SELECT key_value FROM enrollment_keys WHERE revoked = 0 ORDER BY created_at DESC LIMIT 1'
  ).get();
  if (!latest) return { error: 'No enrollment key available — create one in the console', status: 404 };
  return { key: latest.key_value };
}

function readAgentFile(name) {
  const filePath = path.join(agentWindowsDir, name);
  if (!fs.existsSync(filePath)) {
    throw new Error(`Missing agent file: ${name}`);
  }
  return fs.readFileSync(filePath, 'utf8');
}

function psQuote(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

/** Native PowerShell agent script */
downloadRouter.get('/forge_agent.ps1', (_req, res) => {
  try {
    const body = readAgentFile('forge_agent.ps1');
    res.setHeader('Content-Type', 'text/plain; charset=utf-8');
    res.setHeader('Content-Disposition', 'attachment; filename="forge_agent.ps1"');
    res.send(body);
  } catch (e) {
    res.status(404).json({ error: e.message });
  }
});

/**
 * Local file installer (placeholders replaced when key/server provided).
 * Useful for: powershell -File install.ps1
 */
downloadRouter.get('/install.ps1', (req, res) => {
  const keyInfo = resolveEnrollmentKey(req);
  if (keyInfo.error) return res.status(keyInfo.status).json({ error: keyInfo.error });
  const server = publicBase(req);
  try {
    let body = readAgentFile('install.ps1');
    body = body
      .replaceAll('__FORGE_SERVER__', server)
      .replaceAll('__FORGE_KEY__', keyInfo.key);
    res.setHeader('Content-Type', 'text/plain; charset=utf-8');
    res.setHeader('Content-Disposition', 'attachment; filename="install.ps1"');
    res.setHeader('Cache-Control', 'no-store');
    res.send(body);
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});

/**
 * Silent Windows agent install link (no App Store).
 *
 * Elevated PowerShell:
 *   irm http://HOST:8787/download/windows-agent.ps1?key=frg_xxx | iex
 *
 * Or:
 *   powershell -NoProfile -ExecutionPolicy Bypass -Command "iex (irm 'URL')"
 */
downloadRouter.get('/windows-agent.ps1', (req, res) => {
  const keyInfo = resolveEnrollmentKey(req);
  if (keyInfo.error) return res.status(keyInfo.status).json({ error: keyInfo.error });
  const server = publicBase(req);

  const lines = [
    '#Requires -RunAsAdministrator',
    '# Forge Windows agent — silent install bootstrap',
    '# Generated by Forge RMM. No Microsoft Store / App Store required.',
    "$ErrorActionPreference = 'Stop'",
    `$Server = ${psQuote(server)}`,
    `$Key = ${psQuote(keyInfo.key)}`,
    "$InstallDir = Join-Path $env:ProgramFiles 'ForgeAgent'",
    "$TaskName = 'ForgeAgent'",
    "$ConfigPath = Join-Path $env:ProgramData 'ForgeAgent\\config.json'",
    '$AgentUrl = "$Server/download/forge_agent.ps1"',
    '',
    'Write-Host "Forge silent install"',
    'Write-Host "  Server: $Server"',
    'Write-Host "  Target: $InstallDir"',
    '',
    'if (-not (Test-Path -LiteralPath $InstallDir)) {',
    '  New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null',
    '}',
    '',
    "$agentDest = Join-Path $InstallDir 'forge_agent.ps1'",
    'Write-Host "Downloading agent..."',
    'Invoke-WebRequest -Uri $AgentUrl -OutFile $agentDest -UseBasicParsing',
    '',
    "$runner = Join-Path $InstallDir 'run-agent.ps1'",
    "@(",
    "  '$ErrorActionPreference = ''Stop'''",
    "  ('& \"{0}\" run -ConfigPath \"{1}\"' -f $agentDest, $ConfigPath)",
    ") | Set-Content -LiteralPath $runner -Encoding UTF8",
    '',
    'Write-Host "Enrolling device..."',
    '& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $agentDest enroll -Server $Server -Key $Key -ConfigPath $ConfigPath',
    'if ($LASTEXITCODE -and $LASTEXITCODE -ne 0) { throw "Enrollment failed (exit $LASTEXITCODE)" }',
    '',
    'Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue',
    '',
    '$arg = \'-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File "\' + $runner + \'"\'',
    '$action = New-ScheduledTaskAction -Execute \'powershell.exe\' -Argument $arg',
    '$trigger = New-ScheduledTaskTrigger -AtStartup',
    '$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1)',
    '$principal = New-ScheduledTaskPrincipal -UserId \'SYSTEM\' -LogonType ServiceAccount -RunLevel Highest',
    'Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Settings $settings -Principal $principal -Force | Out-Null',
    'Start-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue',
    '',
    'Write-Host ("Done. Scheduled task \'{0}\' is running." -f $TaskName)',
    'Write-Host ("Config: {0}" -f $ConfigPath)',
    '',
  ];

  res.setHeader('Content-Type', 'text/plain; charset=utf-8');
  res.setHeader('Content-Disposition', 'inline; filename="windows-agent.ps1"');
  res.setHeader('Cache-Control', 'no-store');
  res.send(lines.join('\r\n'));
});

/** JSON metadata for the console Enrollment page */
downloadRouter.get('/windows-agent', (req, res) => {
  const keyInfo = resolveEnrollmentKey(req);
  if (keyInfo.error) return res.status(keyInfo.status).json({ error: keyInfo.error });
  const server = publicBase(req);
  const scriptUrl = `${server}/download/windows-agent.ps1?key=${encodeURIComponent(keyInfo.key)}`;
  res.json({
    platform: 'windows',
    enrollment_key: keyInfo.key,
    server,
    download_url: scriptUrl,
    agent_script_url: `${server}/download/forge_agent.ps1`,
    silent_install: `powershell -NoProfile -ExecutionPolicy Bypass -Command "iex (irm '${scriptUrl}')"`,
    notes: [
      'Run in elevated PowerShell (Administrator).',
      'Silent install — no App Store / Microsoft Store.',
      'Installs to Program Files\\ForgeAgent and starts scheduled task ForgeAgent.',
    ],
  });
});
